# MIT License
# Copyright (c) 2026 Heinrich Munz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Turn the tools_week.py measurements into one config per (symbol, side).

The loader (config.yaml) names the process-wide settings; this writes the
per-instrument files it points at, exactly the cTrader shape: one file per
instrument, each carrying only what differs from the loader.

Selection, per symbol and side, over the candidates in
data/week_<sym>.json:

  ADMITTED only if   net + open > 0     - the MARK-TO-MARKET total, not
                                          the realized one. A grid that
                                          banks its winners and still holds
                                          an underwater cluster when the
                                          window stops has not earned what
                                          its realized line shows; measured
                                          on AMZN 2026-08-31, +858 realized
                                          against -678 still open.
                     wins >= MIN_WINS   - one lucky close is not an edge
  RANKED by          wins_per_week      - the stated objective
  TIE-BROKEN by      net

Every admitted file also carries the measurement it came from as a
comment, so the config says where its numbers are from.

The margin sum of all admitted instruments is printed: the paper account
holds 100,000 USD and the peak bound margin is what decides whether the
whole set can actually run side by side.

Usage:
    python tools_make_configs.py                 # write configs/
    python tools_make_configs.py --dry-run       # only the table
"""

from __future__ import annotations

import glob
import json
import os
import sys

from tools_week import CORE_KEYS

HERE = os.path.dirname(os.path.abspath(__file__))
CONFIG_DIR = os.path.join(HERE, "configs")

# A side needs at least this many WINNING clusters in the measured window
# before it is admitted. Two weeks is ten trading days; a single win is
# noise, not a rate.
MIN_WINS = 2


def candidates(symbol: str) -> list[dict]:
    path = os.path.join(HERE, "data", f"week_{symbol.lower()}.json")
    with open(path, "r", encoding="utf-8") as fh:
        return [r for r in json.load(fh) if "error" not in r]


def pick(rows: list[dict], side: str) -> dict | None:
    """Best admitted candidate of one side, or None if none qualifies."""
    ok = [r for r in rows
          if r["side"] == side and r["net"] + r["open_at_end"] > 0
          and r["wins"] >= MIN_WINS]
    if not ok:
        return None
    ok.sort(key=lambda r: (-r["wins_per_week"], -r["net"]))
    return ok[0]


def write_config(row: dict, window: str) -> str:
    dte_min, dte_max = (int(x) for x in row["dte"].split("-"))
    name = f"{row['symbol'].lower()}_{row['side']}"
    path = os.path.join(CONFIG_DIR, f"{name}.yaml")
    lines = [
        "# Instrument config, generated by tools_make_configs.py from the",
        f"# measured search in data/week_{row['symbol'].lower()}.json.",
        f"# Window {window}, hourly RTH bars, real option chain.",
        f"#   wins/week {row['wins_per_week']}  trades/week "
        f"{row['trades_per_week']}  win rate {row['win_rate']}",
        f"#   net {row['net']:+.0f} USD realized, "
        f"{row['net'] + row['open_at_end']:+.0f} USD mark to market",
        f"#   worst cluster {row['worst']:+.0f}"
        f"   equity dd {row['dd']:+.0f}",
        f"#   open at window end {row['open_at_end']:+.0f} USD"
        f"   peak bound margin {row['margin']:.0f} USD",
        "# Ten trading days is a short window - every figure above carries",
        "# that caveat.",
        "",
        f"underlying: {row['symbol']}",
        f"start_long: {'true' if row['side'] == 'long' else 'false'}"
        f"        # {'put' if row['side'] == 'long' else 'call'}"
        f" credit spreads",
        f"dte_min: {dte_min}",
        f"dte_max: {dte_max}",
    ]
    # EVERY grid parameter the measurement used, not just the ones the
    # search varied. A config that leaves one to the loader can be re-run
    # against a different default and silently describe another strategy -
    # measured 2026-08-31, when max_adverse_pct was 5.0 in the search and
    # 0.0 in the portfolio tool.
    if "params" not in row:
        raise SystemExit(
            f"{row['symbol']} {row['side']}: this search result predates the "
            f"self-contained configs and does not record the parameters it "
            f"ran with. Re-run tools_week.py for this symbol.")
    for key in CORE_KEYS:
        if key not in row["params"]:
            raise SystemExit(
                f"{row['symbol']} {row['side']}: the search result has no "
                f"'{key}' - regenerate data/week_*.json with the current "
                f"tools_week.py before writing configs")
        lines.append(f"{key}: {row['params'][key]}")
    lines.append("")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path


def main() -> int:
    dry = "--dry-run" in sys.argv
    files = sorted(glob.glob(os.path.join(HERE, "data", "week_*.json")))
    if not files:
        raise SystemExit("no data/week_*.json - run tools_week.py first")
    if not dry:
        os.makedirs(CONFIG_DIR, exist_ok=True)
    from tools_week import WINDOW, trend_pct
    window = f"{WINDOW[0]}..{WINDOW[1]}"
    print(f"{'sym':6s} {'trend':>7} {'side':>5} {'dte':>5} {'tp':>5} "
          f"{'w/wk':>6} {'rate':>5} {'net':>8} {'margin':>8}  file")
    total_margin, written = 0.0, []
    for path in files:
        sym = os.path.basename(path)[5:-5].upper()
        rows = candidates(sym)
        if not rows:
            print(f"{sym:6s}  no candidate survived the run")
            continue
        try:
            trend = f"{trend_pct(sym, WINDOW):+.2f}%"
        except Exception:                                    # noqa: BLE001
            trend = "-"
        for side in ("long", "short"):
            best = pick(rows, side)
            if best is None:
                print(f"{sym:6s} {trend:>7} {side:>5}   -- not admitted "
                      f"(no candidate with net + open > 0 and "
                      f">= {MIN_WINS} wins)")
                continue
            out = "" if dry else write_config(best, window)
            total_margin += best["margin"]
            written.append(best)
            print(f"{sym:6s} {trend:>7} {side:>5} {best['dte']:>5} "
                  f"{best['tp']:>5.2f} {best['wins_per_week']:>6.2f} "
                  f"{best['win_rate']:>5} {best['net']:>8.0f} "
                  f"{best['margin']:>8.0f}  {os.path.basename(out)}")
    wins = sum(r["wins_per_week"] for r in written)
    net = sum(r["net"] for r in written)
    mtm = sum(r["net"] + r["open_at_end"] for r in written)
    print(f"\n{len(written)} instruments admitted: {wins:.1f} winning "
          f"clusters per week, {net:+.0f} USD realized / "
          f"{mtm:+.0f} USD mark to market over the window")
    print(f"peak bound margin, summed over instruments: "
          f"{total_margin:,.0f} USD")
    print("  (a SUM of per-instrument peaks - the true simultaneous "
          "requirement is at most this and usually lower, because the "
          "peaks do not fall on the same bar)")
    if dry:
        print("\n--dry-run: nothing written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
